Чтобы реализовать обработку исключений в C++, используйте trythrowи catch выражения.

Во-первых, используйте try блок, чтобы заключить одну или несколько инструкций, которые могут вызвать исключение.
